#ifndef _IR_H
#define _IR_H

#define RECEIVER A2

#define KEY_POWER_IR (0xFFA25D)
#define KEY_FUNC_STOP_IR (0xFFE21D)
#define KEY_VOL_ADD_IR (0xFF629D)
#define KEY_FAST_BACK_IR (0xFF22DD)
#define KEY_PAUSE_IR (0xFF02FD)
#define KEY_FAST_FORWARD_IR (0xFFC23D)
#define KEY_DOWN_IR (0xFFE01F)
#define KEY_VOL_DE_IR (0xFFA857)
#define KEY_UP_IR (0xFF906F)
#define KEY_EQ_IR (0xFF9867)
#define KEY_ST_REPT_IR (0xFFB04F)
#define KEY_ZERO (0xFF6897)
#define KEY_ONE (0xFF30CF)
#define KEY_TWO (0xFF18E7)
#define KEY_THREE (0xFF7A85)
#define KEY_FOUR (0xFF10EF)
#define KEY_FIVE (0xFF38C7)
#define KEY_SIX (0xFF5AA5)
#define KEY_SEVEN (0xFF42BD)
#define KEY_EIGTH (0xFF4AB5)
#define KEY_NINE (0xFF52AD)
#define KEY_REPEAT_IR (0xFFFFFFFF)
#define KEY_NUM 21
#define REPEAT 22

unsigned long keyValue[]={KEY_POWER_IR,KEY_FUNC_STOP_IR,KEY_VOL_ADD_IR,KEY_FAST_BACK_IR,KEY_PAUSE_IR,KEY_FAST_FORWARD_IR,
                KEY_DOWN_IR,KEY_VOL_DE_IR,KEY_UP_IR,KEY_EQ_IR,KEY_ST_REPT_IR,KEY_ZERO,KEY_ONE,KEY_TWO,KEY_THREE,KEY_FOUR,KEY_FIVE,
                KEY_SIX,KEY_SEVEN,KEY_EIGTH,KEY_NINE,KEY_REPEAT_IR};
#endif
